apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-backups
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    limits:
      storage: 100Gi
    requests:
      storage: 100Gi
  storageClassName: cinder-backup
  volumeMode: Filesystem
