apiVersion: apphosting.mittwald.cloud/v1
kind: ProjectIngress
metadata:
  name: "{{ .Values.host }}"
spec:
  hostname: "{{ .Values.host }}"
  paths:
    /:
      directory: /
  project:
    name: paperless
  tls:
    type: acme
